
services:
  db:
    image: postgres:17.6
    container_name: movies-pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies_tvshows
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: movies-backend
    depends_on:
      - db
    environment:
      PG_DB_URL: "postgresql://postgres:postgres@db:5432/movies_tvshows"
      PORT: 4112
      NODE_ENV: development
    ports:
      - "4112:4112"
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm run build &&
        npm run start
      "
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
